export enum CARD_TYPES {
  EXPENSE_PLAN = 'EXPENSE_PLAN',
  EXPENSE_FACT = 'EXPENSE_FACT',
  INCOME_FACT = 'INCOME_FACT',
  INCOME_PLAN = 'INCOME_PLAN',
  SAVINGS_PLAN = 'SAVINGS_PLAN',
  SAVINGS_FACT = 'SAVINGS_FACT',
}
