export enum REFETCHES_LIST {
  BALANCES = 'BALANCES',
  CATEGORIES = 'CATEGORIES',
  SAVING_GOALS = 'SAVING_GOALS',
  SAVINGS = 'SAVINGS',
  INCOMES = 'INCOMES',
  EXPENSES = 'EXPENSES',
  USER = 'USER',
}
